name: Run Linters
on: 
  workflow_call:
jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-24.04
    env:
      CODE_DIRS: "adcm_aio_client tests"
    steps:
      - name: Show python
        run: which python
      - name: Show python 3
        run: which python3
      - name: Show pythons
        run: "ls -la /usr/bin | grep python"
      - name: Install poetry
        run: python3.12 -m pip install poetry
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: poetry install --with dev --no-root
      - name: Run ruff lint check
        run: poetry run ruff check $CODE_DIRS
      - name: Run ruff format check
        run: poetry run ruff format --check $CODE_DIRS
      - name: Run pyright check
        run: poetry run pyright $CODE_DIRS

